### ISSUE TITLE
Thany you!

### ISSUE THREAD

**Issue by sife14** [kswiorek/ble-ftms#2]
I just want to say thank you for your amazing work. I have searched for implementation of the FTMS for ESP32 for hours until I found your amazing project. I really like the idea of the virtual gearing.

The only problem I experienced with your implementation, was an unstable connection to the virtual bike trainer software, which I fixed by adding a delay in the main loop. It seems like it was sending data to fast. I don't know if this issue also existed in the original code, since I modified your code quite a bit to fit to my hardware needs.

**Comment by kswiorek** [comment]
I'm glad that I could help. I wanted to share this so I can save people some time, as I spent tens of hours without the help of any examples. 
The delay might have helped - the graphical LCD I'm using takes quite a long time to write to, so the delay creates itself, but without it the loop may indeed run too quickly. I don't like using the "delay" function, because it stops any inputs and the refreshing of the LCD. I would use the something like this: `if millis()%100 { [send data] }` this would send the data every 100ms, but the LCD would still refresh as quickly as it can.

**Comment by doudar** [comment]
I didn't look at the code, but vtaskdelay() should be your go to on the ESP32 as it lets other threads run. Regular delay() blocks anything else from running.
